- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- link:
    ~/.zshrc: zsh/zshrc

- shell:
  - [git submodule update --init --recursive, Installing submodules]
  - command: find . -name install.sh | while read installer ; do chmod u+x "${installer}" ; done
    description: Make installers executable
  - command: find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
    description: Running installers
  - [chsh -s $(which zsh), Making zsh the default shell]
