#!/bin/sh
#
# Quick shortcut to a file manager.
#
# This means that as I travel back and forth between file managers, hey, I don't have
# to re-learn any arcane commands. Neat.
#
# USAGE:
#
#   $ o
#   # => opens the current directory in your file manager
#
#   $ o .
#   $ 0 /usr/local
#   # => opens the specified directory in your file manager
exec "$FILE_MANAGER" "${1:-.}"
