# Environment variables
export DOTFILES=$HOME/.dotfiles

if [ ! -d "$HOME/.dotfiles" ]; then
  # We are running inside a GitHub Codespace
  export DOTFILES=/workspaces/.codespaces/.persistedshare/dotfiles
fi

export EDITOR=code
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export CLICOLOR=true
export PATH="./bin:/usr/local/bin:/usr/local/sbin:$DOTFILES/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/fre"
export PLATIN_JAVA="/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/fre"
export PLUGIN_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/fre"

# Source zinit zsh plugin manager
source $DOTFILES/.zinit/zinit.zsh
autoload -Uz compinit && compinit

# Source config
source $DOTFILES/zsh/config.zsh

# Source aliases
for file in $DOTFILES/**/aliases.zsh; do
  source "$file"
done

# Plugins
zinit for \
  zsh-users/zsh-autosuggestions \
  zdharma/fast-syntax-highlighting \
  fribmendes/geometry \
  b4b4r07/enhancd \
  chrissicool/zsh-256color \
