# Environment variables
if [ ! -d "$HOME/.dotfiles" ] && [ ! -d "/workspaces/.codespaces" ]; then
  echo "ERROR: The dotfiles need to be cloned to ${HOME}/.dotfiles."
  echo "ERROR: If the dotfiles where cloned to a different place, multiple things will break!"
fi

export DOTFILES=$HOME/.dotfiles
if [ -d "/workspaces/.codespaces" ]; then
  # We are running inside a GitHub Codespace. GitHub doesn't clone the dotfiles into ~/.dotfiles.
  export DOTFILES=/workspaces/.codespaces/.persistedshare/dotfiles
fi

export BROWSER=firefox
export EDITOR=code
export LSCOLORS="exfxcxdxbxegedabagacad"
export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43"
export CLICOLOR=true
export PATH="/opt/homebrew/bin:./bin:/usr/local/bin:/usr/local/sbin:$DOTFILES/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/sapmachine-17.jdk/Contents/Home"
export PLATIN_JAVA=$JAVA_HOME
export PLUGIN_HOME=$JAVA_HOME

# Source ~/.profile if it exists
if [ -f ~/.profile ]; then
    source ~/.profile
fi

# Source zinit zsh plugin manager
source $DOTFILES/.zinit/zinit.zsh
autoload -Uz compinit && compinit

# Source config
source $DOTFILES/zsh/config.zsh

# Source key-bindings & completions
source $DOTFILES/zsh/completions.zsh

# Source secrets if the file exists
if [ -f "$DOTFILES/zsh/secrets.zsh" ]; then
  source "$DOTFILES/zsh/secrets.zsh"
fi

# Source aliases
for file in $DOTFILES/**/aliases.zsh; do
  source "$file"
done

# Plugins
zinit for \
  zsh-users/zsh-autosuggestions \
  zdharma/fast-syntax-highlighting \
  fribmendes/geometry \
  chrissicool/zsh-256color \

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
